# Header
menu:
  Home: /
  Archives: /archives
  # Tags: /tags
  Categories: /categories
  Github:
    url: https://github.com/blackstarxing
    icon: github

# Title on top left of menu. Leave empty to use main blog title
menu_title: Don't rush and never settle

# URL of the Home page image
# index_cover: http://www.codeblocq.com/assets/projects/hexo-theme-clean-blog/img/home-bg.jpg
index_cover: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1529827147060&di=9daf466807623fea081eaffa76c5dac6&imgtype=0&src=http%3A%2F%2Fpic1.win4000.com%2Fwallpaper%2F7%2F539fa0f4e65ad.jpg
# Default post title
default_post_title: Untitled

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: blackstarxing
  duoshuo_shortname: blackstar
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Addthis ID
addthis:

# Social Accounts
twitter_url:
twitter_handle:
facebook_url:
weibo_url: http://weibo.com/2959895465/profile?topnav=1&wvr=6&is_all=1
github_url: https://github.com/blackstarxing
gitlab_url:
linkedin_url:
mailto: 